-- =====================================================================
-- V6: Tabla de planos del salón por evento
-- Nota: la columna "data" (binaria) la gestiona Hibernate ddl-auto=update
--       con el tipo correcto para cada dialecto (bytea en PG, binary en H2).
-- =====================================================================

CREATE TABLE IF NOT EXISTS floor_plans (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT       NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size    BIGINT,
    created_at   TIMESTAMP
);

-- Un evento admite un único plano activo
CREATE UNIQUE INDEX IF NOT EXISTS idx_floor_plans_event ON floor_plans(event_id);



